# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        Naive MapReduce
site_description: Naive MapReduce
site_author:      Deyan Dyankov

repo_name:        GitHub
repo_url:         https://github.com/deyandyankov/nmr

theme: material

copyright: Copyright © 2017 Deyan Dyankov

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

docs_dir: 'build'

pages:
  - Home: index.md
#  - Manual:
#    - Installation & Usage: install.md
#    - Valuation: valuation.md
#    - Display & Formatting: display.md
#    - Custom Currencies: custom.md
#    - Rounding: rounding.md
#    - Notes on Performance: performance.md
#  - Reference: reference.md

extra:
  version: 0.5.0
  author:
    github: deyandyankov
    twitter: dyankov
